//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMovilProyecto1.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppMovilProyecto1.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el monto.
        /// </summary>
        internal static string Amount_input {
            get {
                return ResourceManager.GetString("Amount-input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Convertir.
        /// </summary>
        internal static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto convertido:.
        /// </summary>
        internal static string Converted_amount {
            get {
                return ResourceManager.GetString("Converted-amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conversor.
        /// </summary>
        internal static string Converter {
            get {
                return ResourceManager.GetString("Converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto a convertir:.
        /// </summary>
        internal static string Entry_amount {
            get {
                return ResourceManager.GetString("Entry-amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elementos favoritos.
        /// </summary>
        internal static string Favorite_elements {
            get {
                return ResourceManager.GetString("Favorite-elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elementos favoritos.
        /// </summary>
        internal static string Favorite_items {
            get {
                return ResourceManager.GetString("Favorite-items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favoritos.
        /// </summary>
        internal static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto final:.
        /// </summary>
        internal static string Final_amount {
            get {
                return ResourceManager.GetString("Final-amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Divisa....
        /// </summary>
        internal static string SearchBarPlace {
            get {
                return ResourceManager.GetString("SearchBarPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona la divisa destino: .
        /// </summary>
        internal static string Select_dest {
            get {
                return ResourceManager.GetString("Select-dest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona la divisa de origen: .
        /// </summary>
        internal static string Select_origin {
            get {
                return ResourceManager.GetString("Select-origin", resourceCulture);
            }
        }
    }
}
